site_name: Documentation of scaLAPACKe

site_description: "scaLAPACKe -- provide a set of headers and wrappers for scaLAPACK in C"
site_url: https://pierrebeaujean.github.io/scalapacke/
repo_url: "https://github.com/pierre-24/scalapacke"
edit_uri: "blob/dev/docs/"
repo_name: "pierre-24/scalapacke"

nav:
  - Home: index.md
  - About: about.md
  - For developers:
      - Installation: dev/install.md
      - Quickstart: dev/quickstart.md
      - Tutorial: dev/tutorial.md
  - For contributors:
      - Contributing: contrib/CONTRIBUTING.md
      - Important notes: contrib/notes.md


theme:
  name: material
  features:
    - navigation.footer

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - javascript/katex.js


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"