name: Test & publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          make install
      - name: lint
        run: |
          make lint

      - name: Clone scalapack
        run: |
          git clone https://github.com/Reference-ScaLAPACK/scalapack.git
      - name: Build header (C call)
        run: |
          python ./cblacs-header scalapack/ -o cblacs_ccall.h

      - name: Build header (fotran call)
        run: |
          python ./cblacs-header scalapack/ -f -o cblacs_fcall.h

      - name: Upload latest version of headers
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clbacs*.h
          tag: latest
          overwrite: true
          body: "Latest version"
          file_glob: true