name: Release

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Release latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          make install

      - name: Clone scalapack
        run: |
          git clone https://github.com/Reference-ScaLAPACK/scalapack.git
      - name: Build BLACS header
        run: |
          scaLAPACK_create --blacs scalapack/

      - name: Upload latest version of headers
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cblacs.h
          tag: latest
          overwrite: true
          body: "Latest version"