name: Tests

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NPROCS: 2

jobs:
  build:
    name: Tests generate header and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt install libopenmpi-dev libscalapack-openmpi-dev
          make install-dev
      - name: lint
        run: |
          make lint
      - name: Clone scalapack
        run: |
          git clone https://github.com/Reference-ScaLAPACK/scalapack.git

      - name: Build headers and wrappers
        run: |
          cd tests
          scaLAPACK_create --all ../scalapack

      - name: test cblacs
        run: |
          cd tests
          mpicc -o test test_cblacs.c $(pkg-config scalapack-openmpi --libs --cflags) -lm -DFCALLS && mpiexec -n ${{ env.NPROCS }} ./test
          mpicc -o test test_cblacs.c $(pkg-config scalapack-openmpi --libs --cflags) -lm -DCCALLS && mpiexec -n ${{ env.NPROCS }} ./test
          
          mpicc -o test test_pblas.c $(pkg-config scalapack-openmpi --libs --cflags) -lm -DFCALLS && mpiexec -n ${{ env.NPROCS }} ./test
          mpicc -o test test_pblas.c $(pkg-config scalapack-openmpi --libs --cflags) -lm -DCCALLS && mpiexec -n ${{ env.NPROCS }} ./test
